#! /bin/sh

. "$(dirname "$0")/config/programs.sh"

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

. "$(dirname "$0")/config/desktops.sh"
. "$(dirname "$0")/config/scratchpad.sh"

readonly basic_padding=12
readonly window_gap=32
readonly general_padding="$((basic_padding - window_gap))"
readonly monocle_padding="$((-general_padding))"
readonly bar_padding="$((basic_padding))"
readonly bar_position="top"

bspc config border_width 0
bspc config window_gap $window_gap

bspc config top_padding $general_padding
bspc config bottom_padding $general_padding
bspc config left_padding $general_padding
bspc config right_padding $general_padding
bspc config "${bar_position}_padding" "$bar_padding"

bspc config top_monocle_padding $monocle_padding
bspc config right_monocle_padding $monocle_padding
bspc config bottom_monocle_padding $monocle_padding
bspc config left_monocle_padding $monocle_padding
bspc config "${bar_position}_monocle_padding" $((monocle_padding + basic_padding))

bspc config normal_border_color "#121a1b"
bspc config active_border_color "#7d8282"
bspc config focused_border_color "#878c78"
bspc config presel_feedback_color "#7d8282"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config click_to_focus button1
bspc config pointer_follows_monitor true

. "$(dirname "$0")/config/rules.sh"
