[general]
live_config_reload = true
working_directory = "None"
ipc_socket = true
import = ["~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml"]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = false

[terminal.shell]
program = "zsh"

[window]
dynamic_padding = true
opacity = 0.90
option_as_alt = "OnlyLeft"

[window.padding]
x = 8
y = 4
